aliyun/aliyun-openapi-net-sdk

aliyun-net-sdk-core.Tests/Auth/AcsURLEncoder.cs
aliyun-net-sdk-core.Tests/Auth/Sts/GetSessionAccessKeyResponseUnmarshaller.cs

Auth unit tests

---

aliyun-net-sdk-core/Auth/RoaSignatureComposer.cs
aliyun-net-sdk-core/Auth/RpcSignatureComposer.cs

RoaSignatureComposer 与 RpcSignatureComposer  增加静态变量释放函数
用以解决UT之间数据干扰的问题

增加静态变量释放函数

---

aliyun-net-sdk-core.Tests/Auth/Sts/GetSessionAccessKeyRequest.cs
aliyun-net-sdk-core/Auth/Sts/GetSessionAccessKeyRequest.cs

* GetSessionAccessKeyRequest 类增加友元程序集声明
* GetSessionAccessKeyRequest UT

Auth sts ut

---

aliyun-net-sdk-core.Tests/Mock/ACKMock.cs
aliyun-net-sdk-core.Tests/Mock/DateTimeMock.cs
aliyun-net-sdk-core.Tests/Units/Auth/ECSMetadataServiceCredentialsFetcher.cs
aliyun-net-sdk-core.Tests/Units/Auth/InstanceProfileCredentials.cs
aliyun-net-sdk-core.Tests/Units/Auth/InstanceProfileCredentialsProvider.cs
aliyun-net-sdk-core/Auth/ECSMetadataServiceCredentialsFetcher.cs
aliyun-net-sdk-core/Auth/InstanceProfileCredentials.cs
aliyun-net-sdk-core/Auth/InstanceProfileCredentialsProvider.cs

ECSMetadataServiceCredentialsFetcher UT

Units auth

---

aliyun-net-sdk-core.Tests/Mock/ACKMock.cs
aliyun-net-sdk-core.Tests/Mock/DateTimeMock.cs
aliyun-net-sdk-core.Tests/Units/Regions/DescribeEndpointServiceImpl.cs
aliyun-net-sdk-core/Regions/DescribeEndpointServiceImpl.cs

DescribeEndpointServiceImpl UT

Units regions desc

---

aliyun-net-sdk-core.Tests/Units/Auth/InstanceProfileCredentialsProvider.cs

距离过期时间大于10秒时不抛出异常。
距离过期时间大于0秒且小于10秒时抛出ClientException异常。

debug : "SDK.SessionTokenExpired : Current session token has expired."

---

aliyun-net-sdk-core/Profile/DefaultProfile.cs

1. ToList() 
>  debug "System.InvalidOperationException : Collection was modified; enumeration operation may not execute."
2. this.GetEndpointByIEndpoints(regionId, product); 
>  for mock endpoints data

fix DefaultProfile

---

aliyun-net-sdk-core.Tests/Units/Http/UserAgent.cs
aliyun-net-sdk-core/Http/UserAgent.cs
aliyun-net-sdk-core/Utils/StringUtils.cs

User agent

---

aliyun-net-sdk-core.Tests/Units/AcsRequest.cs
aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs
aliyun-net-sdk-core.Tests/Units/Http/UserAgent.cs
aliyun-net-sdk-core/AcsRequest.cs
aliyun-net-sdk-core/DefaultAcsClient.cs
aliyun-net-sdk-core/Http/UserAgent.cs

User agent feature tests

---

aliyun-net-sdk-core.Tests/Units/CommonRpcRequest.cs

Add CommonRpcRequest user agent unit test

---

aliyun-net-sdk-core.Tests/Features/HttpDebug/HttpDebugTest.cs
aliyun-net-sdk-core.Tests/Features/ProfileInitialization.cs
aliyun-net-sdk-core.Tests/Mock/Services/Ecs/DescribeRegions.cs
aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs

Add http debug tests

---

aliyun-net-sdk-core.Tests/Mock/Services/Ecs/DescribeAccessPoints.cs

Rename ecs service

---

aliyun-net-sdk-core/Http/UserAgent.cs

Fix user agent duplicate error

---

aliyun-net-sdk-core/Http/UserAgent.cs

Simplify .net core runtime name to netcoreapp in User-Agent message

---

.travis.yml
appveyor.yml
codecov.yml

Do not execute codecov in feature test(#145)

---

aliyun-sdk-feature-test/APIEncapsulate/APIEncapsulateTest.cs
aliyun-sdk-feature-test/Core/CoreTest.cs
aliyun-sdk-feature-test/Credential/CredentialsTest.cs
aliyun-sdk-feature-test/FeatureTestBase.cs
aliyun-sdk-feature-test/aliyun-sdk-feature-test.csproj
codecov.yml

Add function test

---

aliyun-net-sdk-core.Tests/Units/Auth/ECSMetadataServiceCredentialsFetcher.cs
aliyun-net-sdk-core.Tests/Units/Auth/Provider/DefaultCredentialProvider.cs
aliyun-net-sdk-core.Tests/Units/Auth/STSAssumeRoleSessionCredentialsProvider.cs
aliyun-net-sdk-core.Tests/Units/TestHelper.cs
aliyun-net-sdk-core.Tests/aliyun-net-sdk-core-unit-tests.csproj
aliyun-net-sdk-core/Auth/BasicCredentials.cs
aliyun-net-sdk-core/Auth/BasicSessionCredentials.cs
aliyun-net-sdk-core/Auth/BearerTokenSigner.cs
aliyun-net-sdk-core/Auth/Credential.cs
aliyun-net-sdk-core/Auth/Credential/AccessKeyCredential.cs
aliyun-net-sdk-core/Auth/Credential/BearerTokenCredential.cs
aliyun-net-sdk-core/Auth/Credential/EcsRamRoleCredential.cs
aliyun-net-sdk-core/Auth/Credential/RamRoleArnCredential.cs
aliyun-net-sdk-core/Auth/Credential/RsaKeyPairCredential.cs
aliyun-net-sdk-core/Auth/Credential/StsCredential.cs
aliyun-net-sdk-core/Auth/CredentialsBackupCompatibilityAdaptor.cs
aliyun-net-sdk-core/Auth/ECSMetadataServiceCredentialsFetcher.cs
aliyun-net-sdk-core/Auth/InstanceProfileCredentials.cs
aliyun-net-sdk-core/Auth/InstanceProfileCredentialsProvider.cs
aliyun-net-sdk-core/Auth/KeyPairCredentials.cs
aliyun-net-sdk-core/Auth/LegacyCredentials.cs
aliyun-net-sdk-core/Auth/Provider/DefaultCredentialProvider.cs
aliyun-net-sdk-core/Auth/Provider/RsaKeyPairCredentialProvider.cs
aliyun-net-sdk-core/Auth/STSAssumeRoleSessionCredentialsProvider.cs
aliyun-net-sdk-core/Auth/StaticCredentialsProvider.cs
aliyun-net-sdk-core/DefaultAcsClient.cs
aliyun-net-sdk-core/Profile/DefaultProfile.cs
aliyun-net-sdk-core/Profile/IClientProfile.cs
aliyun-net-sdk-core/Utils/StringUtils.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Add credential chains

---

README.md
README_zh.md
aliyun-net-sdk-core/ChangeLog.txt
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Release Core Version 1.2.1

---

aliyun-net-sdk-core.Tests/Units/Http/UserAgent.cs
aliyun-net-sdk-core/Http/HttpResponse.cs
aliyun-net-sdk-core/Http/UserAgent.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Fix user agent property set error in httpwebrequest

---

codecov.yml

Fix codecov directory error

---

aliyun-net-sdk-core.Tests/Units/Auth/Provider/DefaultCredentialProvider.cs
aliyun-net-sdk-core.Tests/Units/TestHelper.cs
aliyun-sdk-feature-test/Core/CoreTest.cs
aliyun-sdk-feature-test/Credential/CredentialsTest.cs
appveyor.yml

Fix appveyor execute test error

---

README.md
README_zh.md
aliyun-net-sdk-core/ChangeLog.txt
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

RELEASE Core 1.2.2

---

README.md
README_zh.md
aliyun-net-sdk-core.Tests/Units/Auth/Signer.cs
aliyun-net-sdk-core.Tests/Units/RoaAcsRequest.cs
aliyun-net-sdk-core.Tests/Units/RpcAcsRequest.cs
aliyun-net-sdk-core/Auth/BearerTokenSigner.cs
aliyun-net-sdk-core/Auth/RpcSignatureComposer.cs
aliyun-net-sdk-core/Auth/Signer.cs
aliyun-net-sdk-core/DefaultAcsClient.cs
aliyun-net-sdk-core/RoaAcsRequest.cs
aliyun-net-sdk-core/RpcAcsRequest.cs
aliyun-sdk-feature-test/Credential/BearerTokenTest.cs
aliyun-sdk-feature-test/FeatureTestBase.cs
aliyun-sdk-feature-test/aliyun-sdk-feature-test.csproj

Add bearertoken support

---

aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs
aliyun-net-sdk-core.Tests/Units/Http/HttpRequest.cs
aliyun-net-sdk-core.Tests/Units/Http/HttpResponse.cs
aliyun-net-sdk-core/Auth/ECSMetadataServiceCredentialsFetcher.cs
aliyun-net-sdk-core/CommonRequest.cs
aliyun-net-sdk-core/DefaultAcsClient.cs
aliyun-net-sdk-core/Http/HttpRequest.cs
aliyun-net-sdk-core/Http/HttpResponse.cs
aliyun-sdk-feature-test/APIEncapsulate/APIEncapsulateTest.cs
aliyun-sdk-feature-test/Core/CoreTest.cs
aliyun-sdk-feature-test/FeatureTestBase.cs
aliyun-sdk-feature-test/Timeout/TimeoutTest.cs

Add timeout feature

---

README.md
README_zh.md

Update timeout and http debug feature readme

---

README.md
README_zh.md
aliyun-net-sdk-core/ChangeLog.txt
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Release Core version 1.2.3

---

appveyor.yml

Add Visual Studio 2015 into CI

---

README.md
README_zh.md
aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs
aliyun-net-sdk-core.Tests/Units/Http/HttpRequest.cs
aliyun-net-sdk-core.Tests/Units/Http/HttpResponse.cs
aliyun-net-sdk-core/DefaultAcsClient.cs
aliyun-net-sdk-core/Http/HttpRequest.cs
aliyun-net-sdk-core/Http/HttpResponse.cs

Ignore https certificate verification

---

aliyun-net-sdk-core/ChangeLog.txt
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Release Core Version 1.2.4

---

aliyun-net-sdk-core.Tests/Units/Auth/Credential.cs
aliyun-net-sdk-core.Tests/Units/Auth/Credential/AccessKeyCredential.cs
aliyun-net-sdk-core.Tests/Units/Auth/Credential/RamRoleArnCredential.cs
aliyun-net-sdk-core.Tests/Units/Auth/Credential/StsCredential.cs
aliyun-net-sdk-core.Tests/Units/Auth/LegacyCredentials.cs
aliyun-net-sdk-core.Tests/Units/Auth/Provider/DefaultCredentialProvider.cs
aliyun-net-sdk-core.Tests/Units/Auth/Provider/RsaKeyPairCredentialProvider.cs
aliyun-net-sdk-core.Tests/Units/Auth/STSAssumeRoleSessionCredentialsProvider.cs
aliyun-net-sdk-core.Tests/Units/Auth/StaticCredentialsProvider.cs
aliyun-net-sdk-core/Auth/BearerTokenSigner.cs
aliyun-net-sdk-core/Auth/Credential/AccessKeyCredential.cs
aliyun-net-sdk-core/Auth/Credential/BearerTokenCredential.cs
aliyun-net-sdk-core/Auth/Credential/EcsRamRoleCredential.cs
aliyun-net-sdk-core/Auth/Credential/RamRoleArnCredential.cs
aliyun-net-sdk-core/Auth/Credential/RsaKeyPairCredential.cs
aliyun-net-sdk-core/Auth/Credential/StsCredential.cs
aliyun-net-sdk-core/Auth/ECSMetadataServiceCredentialsFetcher.cs
aliyun-net-sdk-core/Auth/Provider/DefaultCredentialProvider.cs
aliyun-net-sdk-core/Auth/Provider/RsaKeyPairCredentialProvider.cs
aliyun-net-sdk-core/Auth/STSAssumeRoleSessionCredentialsProvider.cs

Add credential unit test patch

---

.travis.yml
aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs
aliyun-net-sdk-core.Tests/Units/Http/HttpRequest.cs
aliyun-net-sdk-core.Tests/Units/Http/HttpResponse.cs
aliyun-net-sdk-core.Tests/Units/Http/HttpWebProxy.cs
aliyun-net-sdk-core/DefaultAcsClient.cs
aliyun-net-sdk-core/Http/HttpRequest.cs
aliyun-net-sdk-core/Http/HttpResponse.cs
aliyun-net-sdk-core/Http/HttpWebProxy.cs
aliyun-net-sdk-core/Http/ProxyType.cs
aliyun-sdk-feature-test/HttpProxy/HttpProxyTest.cs
appveyor.yml

Add http proxy feature

---

aliyun-net-sdk-core/Http/UserAgent.cs
aliyun-net-sdk-core/Utils/StringUtils.cs

Make StringUtils obsolete and use String.IsNullOrEmpty instead

---

aliyun-net-sdk-core.Tests/Units/Auth/Provider/DefaultCredentialProvider.cs
aliyun-net-sdk-core/Auth/Provider/DefaultCredentialProvider.cs

Remove bearertoken from ini config

---

aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs
aliyun-net-sdk-core/DefaultAcsClient.cs

fix method accessiblity error

---

aliyun-net-sdk-core/ChangeLog.txt
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Release Core 1.2.5

---

.travis.yml
aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs
aliyun-net-sdk-core.Tests/Units/Http/HttpWebProxy.cs
aliyun-net-sdk-core/DefaultAcsClient.cs
aliyun-net-sdk-core/Http/HttpWebProxy.cs
aliyun-sdk-feature-test/HttpProxy/HttpProxyTest.cs

Refactor http proxy

---

aliyun-net-sdk-core/ChangeLog.txt
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Release core 1.2.6

---

README.md
README_zh.md

Update http proxy readme

---

aliyun-sdk-feature-test/HttpProxy/HttpProxyTest.cs

Add http proxy feature test

---

aliyun-sdk-feature-test/APIEncapsulate/APIEncapsulateTest.cs
aliyun-sdk-feature-test/Core/CoreTest.cs
aliyun-sdk-feature-test/Credential/BearerTokenTest.cs
aliyun-sdk-feature-test/Credential/CredentialsTest.cs
aliyun-sdk-feature-test/EndPoint/EndPointTest.cs
aliyun-sdk-feature-test/ErrorHandler/ErrorHandlingTest.cs
aliyun-sdk-feature-test/FeatureTestBase.cs
aliyun-sdk-feature-test/HttpDebug/HttpDebugTest.cs
aliyun-sdk-feature-test/HttpProxy/HttpProxyTest.cs
aliyun-sdk-feature-test/Timeout/TimeoutTest.cs

Add feature test

---

aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs

Clear env proxy value after execute test

---

aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs
aliyun-net-sdk-core.Tests/aliyun-net-sdk-core-unit-tests.csproj
aliyun-net-sdk-core/DefaultAcsClient.cs
aliyun-sdk-feature-test/HttpProxy/HttpProxyTest.cs

Fix test error

---

aliyun-net-sdk-core/Auth/HmacSHA1Signer.cs
aliyun-net-sdk-core/Auth/SHA256withRSASigner.cs
aliyun-net-sdk-core/Http/HttpResponse.cs
aliyun-net-sdk-core/Reader/JsonReader.cs
aliyun-net-sdk-core/Reader/XmlReader.cs
aliyun-net-sdk-core/Regions/InternalEndpointsParser.cs
aliyun-net-sdk-core/Utils/ParameterHelper.cs

Fix warnings from https://www.nuget.org/packages/IDisposableAnalyzers/

Dispose IDisposables to prevent protential memory leak

---

aliyun-net-sdk-core.Tests/Units/Profile/DefaultProfile.cs
aliyun-net-sdk-core/Auth/HmacSHA1Signer.cs
aliyun-net-sdk-core/Auth/SHA256withRSASigner.cs
aliyun-net-sdk-core/Http/HttpResponse.cs
aliyun-net-sdk-core/Reader/JsonReader.cs
aliyun-net-sdk-core/Reader/XmlReader.cs
aliyun-net-sdk-core/Regions/InternalEndpointsParser.cs
aliyun-net-sdk-core/Utils/ParameterHelper.cs
aliyun-sdk-feature-test/APIEncapsulate/APIEncapsulateTest.cs
aliyun-sdk-feature-test/Credential/CredentialsTest.cs

Prevent memory leak

---

README-CN.md
README.md
docs/4-Timeout-CN.md
docs/4-Timeout-EN.md
docs/5-Packages-CN.md
docs/5-Packages-EN.md

Update readme patch

---

README-CN.md
README.md

Readme update patch

---

aliyun-net-sdk-slb/ChangeLog.txt
aliyun-net-sdk-slb/aliyun-net-sdk-slb.vs2017.csproj

Upgrade Slb Package Version to 3.2.41

Release slb 3.2.41

---

aliyun-net-sdk-core.Tests/Units/Auth/InstanceProfileCredentialsProvider.cs
aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs
aliyun-net-sdk-core.Tests/Units/Utils/SerilogHelperTest.cs
aliyun-net-sdk-core/Auth/InstanceProfileCredentialsProvider.cs
aliyun-net-sdk-core/DefaultAcsClient.cs
aliyun-net-sdk-core/Http/HttpResponse.cs
aliyun-net-sdk-core/Profile/DefaultProfile.cs
aliyun-net-sdk-core/Utils/DictionaryUtil.cs
aliyun-net-sdk-core/Utils/EnvironmentUtil.cs
aliyun-net-sdk-core/Utils/Logger.cs
aliyun-net-sdk-core/Utils/SerilogHelper.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj
aliyun-sdk-feature-test/APIEncapsulate/APIEncapsulateTest.cs

Feature add logger

---

aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs

Unit test namespace correct

---

README-CN.md
README.md
docs/5-Packages-CN.md
docs/5-Packages-EN.md
docs/6-Log-CN.md
docs/6-Log-EN.md

Add logger readme

---

aliyun-sdk-feature-test/Timeout/TimeoutTest.cs

Feature test assert batch

---

aliyun-sdk-feature-test/aliyun-sdk-feature-test.csproj

Fix visual studio 2017 build project error

---

aliyun-net-sdk-core.Tests/Units/Auth/Provider/DefaultCredentialProvider.cs
aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs
aliyun-net-sdk-core.Tests/Units/Utils/SerilogHelperTest.cs
aliyun-net-sdk-core/Auth/Provider/DefaultCredentialProvider.cs
aliyun-net-sdk-core/Utils/EnvironmentUtil.cs
aliyun-sdk-feature-test/ErrorHandler/ErrorHandlingTest.cs

Refactor environment util

---

README-CN.md
README.md
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj
docs/1-Verify-CN.md
docs/5-Packages-CN.md
docs/5-Packages-EN.md
docs/6-Log-CN.md

Alibaba Cloud SDK for **C#** replace to Alibaba Cloud SDK for **.NET**

SDK namespace correct

---

aliyun-net-sdk-core.Tests/Units/Auth/BasicCredentials.cs
aliyun-net-sdk-core.Tests/Units/Auth/BasicSessionCredentials.cs
aliyun-net-sdk-core.Tests/Units/Auth/BearerTokenCredentialTest.cs
aliyun-net-sdk-core.Tests/Units/Auth/Credential.cs
aliyun-net-sdk-core.Tests/Units/Auth/InstanceProfileCredentialsProvider.cs
aliyun-net-sdk-core.Tests/Units/Auth/KeyPairCredentials.cs
aliyun-net-sdk-core.Tests/Units/Auth/Provider/AccessKeyCredentialProviderTest.cs
aliyun-net-sdk-core.Tests/Units/Auth/Provider/DefaultCredentialProviderTest.cs
aliyun-net-sdk-core.Tests/Units/Auth/Provider/RsaKeyPairCredentialProvider.cs
aliyun-net-sdk-core.Tests/Units/TestHelper.cs
aliyun-net-sdk-core/Auth/Credential/BasicSessionCredentials.cs
aliyun-net-sdk-core/Auth/Credential/Credential.cs
aliyun-net-sdk-core/Auth/Credential/InstanceProfileCredentials.cs
aliyun-net-sdk-core/Auth/Provider/DefaultCredentialProvider.cs
aliyun-net-sdk-core/Auth/Provider/ECSMetadataServiceCredentialsFetcher.cs
aliyun-net-sdk-core/Auth/Provider/InstanceProfileCredentialsProvider.cs
aliyun-net-sdk-core/Auth/Provider/RsaKeyPairCredentialProvider.cs
aliyun-net-sdk-core/Auth/Provider/STSAssumeRoleSessionCredentialsProvider.cs

Credential refactor

---

README-CN.md
README.md
docs/6-Log-CN.md
docs/6-Log-EN.md
docs/7-Client-CN.md
docs/7-Client-EN.md

Credential readme

---

aliyun-net-sdk-core.Tests/Units/Auth/BearerTokenCredentialTest.cs
aliyun-net-sdk-core.Tests/Units/Auth/InstanceProfileCredentials.cs
aliyun-net-sdk-core.Tests/Units/Auth/Provider/BearerTokenCredentialProviderTest.cs
aliyun-net-sdk-core/Auth/Provider/BearerTokenCredentialProvider.cs
aliyun-sdk-feature-test/Credential/BearerTokenTest.cs

BearerToken credential provider refactor

---

aliyun-net-sdk-core.Tests/Units/Auth/STSAssumeRoleSessionCredentialsProvider.cs
aliyun-net-sdk-core/Auth/Provider/STSAssumeRoleSessionCredentialsProvider.cs
aliyun-sdk-feature-test/Credential/CredentialsTest.cs

Support policy in RamRoleCredential

---

aliyun-net-sdk-core/ChangeLog.txt
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Core release version1.2.8

---

aliyun-net-sdk-core.Tests/Units/Utils/DictionaryUtil.cs
aliyun-net-sdk-core/Utils/DictionaryUtil.cs

Add generic method support in dictionary util

---

docs/6-Log-CN.md
docs/6-Log-EN.md

Fix log readme incorrect link

---

aliyun-net-sdk-core.Tests/Units/Auth/Provider/DefaultCredentialProviderTest.cs
aliyun-net-sdk-core.Tests/Units/TestHelper.cs
aliyun-net-sdk-core.Tests/Units/Utils/IniFileHelperTest.cs
aliyun-net-sdk-core.Tests/aliyun-net-sdk-core-unit-tests.csproj
aliyun-net-sdk-core/Auth/Provider/DefaultCredentialProvider.cs
aliyun-net-sdk-core/Utils/IniFileHelper.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Ini 文件解析的重构，消除引用第三方库带来的警告，改用本地解析。

Ini file resolve refactor

---

aliyun-net-sdk-dm/ChangeLog.txt
aliyun-net-sdk-dm/aliyun-net-sdk-dm-overseas.vs2017.csproj

DM product release version 4.7.2

---

.travis.yml
aliyun-net-sdk-core/AcsRequest.cs
aliyun-net-sdk-core/Auth/Credential/BasicCredentials.cs
aliyun-net-sdk-core/Auth/Credential/BasicSessionCredentials.cs
aliyun-net-sdk-core/Auth/CredentialsBackupCompatibilityAdaptor.cs
aliyun-net-sdk-core/Auth/Signer/Signer.cs
aliyun-net-sdk-core/Http/UserAgent.cs
aliyun-net-sdk-core/RoaAcsRequest.cs
aliyun-net-sdk-core/RpcAcsRequest.cs
aliyun-net-sdk-core/Utils/CacheTimeHelper.cs
aliyun-net-sdk-core/Utils/SerilogHelper.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2015.csproj
aliyun-net-sdk-core/packages.config
aliyun-net-sdk.vs2015.sln
appveyor.yml

Support build on visual studio 2015 with the target framework 461

---

.gitignore
aliyun-net-sdk-core/ChangeLog.md
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj
docs/0-Requirements-CN.md
docs/0-Requirements-EN.md

Release Core version 1.3.0

---

aliyun-net-sdk-core/DefaultAcsClient.cs

Fix unicode escape error in json resolution

---

aliyun-net-sdk-core/ChangeLog.md
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Core Release 1.3.1

---

aliyun-net-sdk-core.Tests/aliyun-net-sdk-core-unit-tests.csproj
aliyun-net-sdk-core/Auth/ShaHmac1.cs
aliyun-net-sdk-core/Auth/ShaHmac256.cs
aliyun-net-sdk-core/Properties/AssemblyInfo.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj
aliyun-sdk-feature-test/EndPoint/EndPointTest.cs
aliyun-sdk-feature-test/aliyun-sdk-feature-test.csproj

Multiple framework support

---

aliyun-net-sdk-core/ChangeLog.md
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Core release version 1.3.2

---

CONTRIBUTING.md
README-CN.md
README.md
docs/0-Requirements-CN.md
docs/0-Requirements-EN.md

发布日志：
1, Update the docs and readme

CORE SDK Auto Released By yinxi

---

aliyun-net-sdk-core/ChangeLog.md
aliyun-net-sdk-core/Properties/AssemblyInfo.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

发布日志：
1, Core release version 1.3.6

CORE SDK Auto Released By yinxi Version 1.3.6

---

aliyun-net-sdk-core/Utils/EnvironmentUtil.cs

Remove duplicate env code

---

aliyun-sdk-feature-test/APIEncapsulate/APIEncapsulateTest.cs
aliyun-sdk-feature-test/aliyun-sdk-feature-test.csproj

Fix ft error

---

aliyun-net-sdk-core/Regions/endpoints.xml

dbs 的 产品缺少相关 endpoint 数据，考虑先采取加入到静态 xml endpoint 文件中。

Add dbs endpoint to static json file

---

aliyun-net-sdk-core/ChangeLog.md
aliyun-net-sdk-core/Properties/AssemblyInfo.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Core release version 1.3.7

---

.travis.yml

Fix travis unary operator expected

---

aliyun-net-sdk-core.Tests/Units/DefaultAcsClient.cs
aliyun-net-sdk-core.Tests/Units/Http/HttpResponse.cs
aliyun-net-sdk-core/Auth/Provider/ECSMetadataServiceCredentialsFetcher.cs
aliyun-net-sdk-core/DefaultAcsClient.cs
aliyun-net-sdk-core/Http/HttpResponse.cs
aliyun-net-sdk-core/Regions/DescribeEndpointServiceImpl.cs
aliyun-sdk-feature-test/APIEncapsulate/APIEncapsulateTest.cs

Add endpoint info in exception message

---

README-CN.md
README.md

Readme file format

---

aliyun-net-sdk-core.Tests/Units/Regions/InternalEndpointsParser.cs
aliyun-net-sdk-core.Tests/Units/Utils/IniFileHelperTest.cs
aliyun-net-sdk-core.Tests/Units/Utils/StringUtilTest.cs

Add uncoved code unit test

---

aliyun-net-sdk-core/ChangeLog.md
aliyun-net-sdk-core/Properties/AssemblyInfo.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Core release version 1.4.0

---

aliyun-net-sdk-core/ChangeLog.md
aliyun-net-sdk-core/Properties/AssemblyInfo.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Core release version 1.5.0

---

aliyun-net-sdk-core/Http/HttpResponse.cs

Fix content type will null error

---

aliyun-net-sdk-core/ChangeLog.md
aliyun-net-sdk-core/Properties/AssemblyInfo.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Core release version 1.5.1

---

aliyun-net-sdk-core/RpcAcsRequest.cs

Fixed URL builder

---

appveyor.yml

Add Image Visual Studio 2019 in appveyor.yml

Add Image Visual Studio 2019 in appveyor.yml

---

aliyun-net-sdk-core/Auth/RoaSignatureComposer.cs

fix signatureComposer

---

aliyun-net-sdk-core/ChangeLog.md
aliyun-net-sdk-core/Properties/AssemblyInfo.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Core release version 1.5.4

---

aliyun-sdk-feature-test/aliyun-sdk-feature-test.csproj
aliyun-sdk-feature-test/xunit.runner.json

fixed run ft failed.

---

aliyun-net-sdk-core/Profile/IClientProfile.cs
aliyun-net-sdk-core/Regions/DescribeEndpointServiceImpl.cs

* 增加访问 `Location` 的超时时间
* 补齐 `IClientProfile` 接口的方法约定

improved location timeout

---

aliyun-net-sdk-core.Tests/Units/Http/HttpRequest.cs
aliyun-net-sdk-core/Http/HttpRequest.cs

* 修复`Get` 方式请求被设置 `Content-Length` 的问题

fixed content-length

---

aliyun-net-sdk-core/Utils/DictionaryUtil.cs

fixed dict.add

---

docs/8-Endpoint-CN.md
docs/8-Endpoint-EN.md

fixed doc endpoint

---

aliyun-net-sdk-core.Tests/Units/AcsRequest.cs
aliyun-net-sdk-core/AcsRequest.cs

* 设置null或者空字符串时不进行正则判断
* 增加测试用例

fixed region regex

---

aliyun-net-sdk-core/DefaultAcsClient.cs

* Supported Header `x-acs-version`
* Supported Header `x-acs-action`

supported header x_acs_

---

README-CN.md
README.md

update OpenAPI explorer link

---

.github/workflows/ci.yml

use github actions

---

aliyun-net-sdk-core/ChangeLog.md
aliyun-net-sdk-core/Properties/AssemblyInfo.cs
aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj

Bump 1.6.2

---

.github/workflows/ci.yml
aliyun-net-sdk-core.Tests/Units/Auth/ECSMetadataServiceCredentialsFetcher.cs
aliyun-net-sdk-core.Tests/Units/Auth/InstanceProfileCredentialsProvider.cs
aliyun-net-sdk-core/Auth/Provider/ECSMetadataServiceCredentialsFetcher.cs
aliyun-net-sdk-core/Auth/Provider/InstanceProfileCredentialsProvider.cs
aliyun-net-sdk-core/Utils/AuthUtils.cs

feat: support IMDSv2 for ECS metadata
